# Generated by Django 2.2.4 on 2019-08-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('TR', 'TRAVEL'), ('MT', 'MOVIE-SERIES'), ('BK', 'BOOK'), ('GM', 'GAME'), ('CD', 'CODING'), ('AV', 'AVIATION')], default='TR', max_length=2),
        ),
    ]
